# in _config.yml
title: "Writing"
author: "Mayukh Deb"
copyright: "2026"

execute:
  execute_notebooks: "auto"

repository:
  url                       : "https://github.com/mayukhdeb/codebook"  # Online location of your book
  path_to_book              : .  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

html:
  google_analytics_id: G-3Q6LDVNS0X
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://mayukhdeb.github.io/writing
  favicon: images/favicon.ico
  use_fullscreen_button: false
  comments:
    hypothesis: false
  extra_footer: ""

launch_buttons:
  thebe             : true
  notebook_interface: classic

thebe_config:
  repository_url : "https://github.com/mayukhdeb/codebook"  # Online location of your book
  path_to_book   : "docs/"  # Optional path to your book, relative to the repository root
  branch         : main  # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    - colon_fence
    - substitution
    - dollarmath
    - deflist
    - html_image

sphinx:
  extra_extensions:
  - sphinxext.opengraph
  config:
    html_favicon: images/favicon.ico
    html_js_files:
      - custom.js
    pygments_style: native
    ogp_site_url: "https://mayukhdeb.github.io/writing"
    ogp_image: "https://mayukhdeb.com/_images/unicorn.png"
    ogp_description_length: 200
